### ISSUE TITLE
iOS PrivacyInfo

### ISSUE THREAD

**Issue by xamplum** [RocketChat/rn-user-defaults#4]
Hi,

a PrivacyInfo needs to be added. See
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

**Comment by dnlsilva** [comment]
I don't know if you use this library, but it hasn't been maintained for years and we no longer use it in the app.
So there is no reason why this should be done.

**Comment by xamplum** [comment]
@GleidsonDaniel should the repo then not be archived? Or shouldn't there at least be a note to that effect in the readme?!
